@EmpAPI_HostAddress = http://localhost:5295

GET {{EmpAPI_HostAddress}}/weatherforecast/
Accept: application/json
###
GET {{EmpAPI_HostAddress}}/api/Employees
Accept: application/json

###
POST{{EmpAPI_HostAddress}}/api/Employees
Accept: application/json
